detectors:
  IrresponsibleModule:
    enabled: false

  TooManyInstanceVariables:
    max_instance_variables: 8

  TooManyStatements:
    max_statements: 7

  DuplicateMethodCall:
    enabled: false
    
  InstanceVariableAssumption:
    enabled: false

  ControlParameter:
    enabled: false

  NilCheck:
    enabled: false

directories:
  "app/models":
    Attribute:
      enabled: false
    FeatureEnvy:
      enabled: false

exclude_paths:
  - app/channels/
  - config/
  - db/
  - app/controllers/users/omniauth_callbacks_controller.rb