detectors:
  IrresponsibleModule:
      enabled: false
      exclude: []
  TooManyInstanceVariables:
      max_instance_variables: 8
  TooManyStatements:
    enabled: true
    exclude:
    - initialize
    max_statements: 7
  DuplicateMethodCall:
    max_calls: 2
  InstanceVariableAssumption:
      enabled: false
exclude_paths:
  - app/channels/
  - config/
  - db/
  - app/controllers/users/omniauth_callbacks_controller.rb