require: rubocop-rspec

Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 24

Metrics/ClassLength:
  Max: 100

Metrics/BlockLength:
  Max: 70

Metrics/MethodLength:
  Max: 10
  Exclude:
    - "app/models/ability.rb"

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - "**/checkout_page_spec.rb"

Lint/AssignmentInCondition:
  Exclude:
    - "app/models/user.rb"

RSpec/NamedSubject:
  Exclude:
    - "**/checkout_controller_spec.rb"

RSpec/LeakyConstantDeclaration:
  Exclude:
    - "**/checkout_controller_spec.rb"

RSpec/ExampleLength:
  Exclude:
    - "**/settings_page_spec.rb"
    - "**/checkout_page_spec.rb"

RSpec/LetSetup:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - bin/**/*
    - node_modules/**/*
    - db/**/*
    - config/**/*
    - app/channels/**/*
    - 'config.ru'
    - app/controllers/users/omniauth_callbacks_controller.rb