require: rubocop-rspec

Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 10

Metrics/BlockLength:
  Max: 50

Metrics/ClassLength:
  Max: 100

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

AllCops:
  Exclude:
    - bin/**/*
    - node_modules/**/*
    - db/**/*
    - config/**/*
    - app/channels/**/*
    - 'config.ru'
    - app/controllers/users/omniauth_callbacks_controller.rb