
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookstore_development

test:
  <<: *default
  database: bookstore_test

production:
  <<: *default
  host: localhost
  database: bookstore_production
  username: <%= ENV['BOOKSTORE_NAME'] %>
  password: <%= ENV['BOOKSTORE_DATABASE_PASSWORD'] %>
